// Auto-generated by stellar-contracts-kit
// Contract : CAD4HUNGVAMZLQ4JOR3HFLDSWVZRGOBEJGPBCO2EEU6PEFOITQ4EE4D2
// Network  : testnet
// Re-run `npx sck generate` to update after a contract upgrade.

// Contract Interface

/**
 * @typedef {Object} hello
 * @property {import('stellar-contracts-kit').ContractMethodFn<Array<string>, [to: string]>} hello
 */

export const CONTRACT_ID = 'CAD4HUNGVAMZLQ4JOR3HFLDSWVZRGOBEJGPBCO2EEU6PEFOITQ4EE4D2'
