// Auto-generated by stellar-contracts-kit
// Example usage for hello
// Contract : CAD4HUNGVAMZLQ4JOR3HFLDSWVZRGOBEJGPBCO2EEU6PEFOITQ4EE4D2
// Network  : testnet
// @ts-check

import { StellarContractsKit } from 'stellar-contracts-kit'
// Types file: ./contracts/hello.js. Update the path below if using snippets elsewhere.
import { CONTRACT_ID } from './hello.js'

const kit = new StellarContractsKit({ network: 'testnet' })

// Connect wallet (opens picker modal if no wallet specified)
const { address } = await kit.connect()
console.log('Connected:', address)

// Load the contract client
const contract = await kit.contract(CONTRACT_ID)

// hello(to: string) -> Array<string>
const { txHash: helloTxHash, result: helloResult } = await contract.hello.invoke(
  '',  // to: string
)
console.log('hello txHash:', helloTxHash, 'result:', helloResult)
