// Auto-generated by stellar-contracts-kit
// Contract : CDERI5KIEWKO3MMZDPUFWYDDH4JTUXYSX2SBYMVYBSZUTT25W7TXVHCU
// Network  : testnet
// Re-run `npx sck generate` to update after a contract upgrade.

// Custom Types

/** @typedef {{ content: string, id: bigint, title: string }} Note */

// Contract Interface

/**
 * @typedef {Object} notes
 * @property {import('stellar-contracts-kit').ContractMethodFn<Array<Note>, []>} get_notes
 * @property {import('stellar-contracts-kit').ContractMethodFn<string, [title: string, content: string]>} create_note
 * @property {import('stellar-contracts-kit').ContractMethodFn<string, [id: bigint]>} delete_note
 */

export const CONTRACT_ID = 'CDERI5KIEWKO3MMZDPUFWYDDH4JTUXYSX2SBYMVYBSZUTT25W7TXVHCU'
