// Auto-generated by stellar-contracts-kit
// Example usage for notes
// Contract : CDERI5KIEWKO3MMZDPUFWYDDH4JTUXYSX2SBYMVYBSZUTT25W7TXVHCU
// Network  : testnet
// @ts-check

import { StellarContractsKit } from 'stellar-contracts-kit'
// Types file: ./contracts/notes.js. Update the path below if using snippets elsewhere.
import { CONTRACT_ID } from './notes.js'

const kit = new StellarContractsKit({ network: 'testnet' })

// Connect wallet (opens picker modal if no wallet specified)
const { address } = await kit.connect()
console.log('Connected:', address)

// Load the contract client
const contract = await kit.contract(CONTRACT_ID)

// get_notes() -> Array<Note>
const { result: get_notesResult } = await contract.get_notes.read()
console.log('get_notes:', get_notesResult)

// create_note(title: string, content: string) -> string
const { txHash: create_noteTxHash, result: create_noteResult } = await contract.create_note.invoke(
  '',  // title: string
  '',  // content: string
)
console.log('create_note txHash:', create_noteTxHash, 'result:', create_noteResult)

// delete_note(id: bigint) -> string
const { txHash: delete_noteTxHash, result: delete_noteResult } = await contract.delete_note.invoke(
  0n,  // id: bigint
)
console.log('delete_note txHash:', delete_noteTxHash, 'result:', delete_noteResult)
