// Auto-generated by stellar-contracts-kit
// Contract : CBOXUHO7WVFINZ472NPHOK6I5DHEYC3HH5MMAOZQJVVW43IGS5VYR5CV
// Network  : mainnet
// Re-run `npx sck generate` to update after a contract upgrade.

// Custom Types

/** @typedef {{ content: string, id: bigint, title: string }} Note */

// Contract Interface

/**
 * @typedef {Object} notes
 * @property {import('stellar-contracts-kit').ContractMethodFn<Array<Note>, []>} get_notes
 * @property {import('stellar-contracts-kit').ContractMethodFn<string, [title: string, content: string]>} create_note
 * @property {import('stellar-contracts-kit').ContractMethodFn<string, [id: bigint]>} delete_note
 */

export const CONTRACT_ID = 'CBOXUHO7WVFINZ472NPHOK6I5DHEYC3HH5MMAOZQJVVW43IGS5VYR5CV'
